import hakkimda_img from "../assets/hakkimda_img.svg"

export const cinsiyet = [
  { value: "kadın", label: "Kadın" },
  { value: "erkek", label: "Erkek" },
]

export const sehirler = [
  { value: "adana", label: "Adana" },
  { value: "adiyaman", label: "Adıyaman" },
  { value: "afyonkarahisar", label: "Afyonkarahisar" },
  { value: "agri", label: "Ağrı" },
  { value: "amasya", label: "Amasya" },
  { value: "ankara", label: "Ankara" },
  { value: "antalya", label: "Antalya" },
  { value: "artvin", label: "Artvin" },
  { value: "aydin", label: "Aydın" },
  { value: "balikesir", label: "Balıkesir" },
  { value: "bilecik", label: "Bilecik" },
  { value: "bingol", label: "Bingöl" },
  { value: "bitlis", label: "Bitlis" },
  { value: "bolu", label: "Bolu" },
  { value: "burdur", label: "Burdur" },
  { value: "bursa", label: "Bursa" },
  { value: "canakkale", label: "Çanakkale" },
  { value: "cankiri", label: "Çankırı" },
  { value: "corum", label: "Çorum" },
  { value: "denizli", label: "Denizli" },
  { value: "diyarbakir", label: "Diyarbakır" },
  { value: "edirne", label: "Edirne" },
  { value: "elazig", label: "Elazığ" },
  { value: "erzincan", label: "Erzincan" },
  { value: "erzurum", label: "Erzurum" },
  { value: "eskisehir", label: "Eskişehir" },
  { value: "gaziantep", label: "Gaziantep" },
  { value: "giresun", label: "Giresun" },
  { value: "gumushane", label: "Gümüşhane" },
  { value: "hakkari", label: "Hakkari" },
  { value: "hatay", label: "Hatay" },
  { value: "isparta", label: "Isparta" },
  { value: "mersin", label: "Mersin" },
  { value: "istanbul", label: "İstanbul" },
  { value: "izmir", label: "İzmir" },
  { value: "kars", label: "Kars" },
  { value: "kastamonu", label: "Kastamonu" },
  { value: "kayseri", label: "Kayseri" },
  { value: "kirklareli", label: "Kırklareli" },
  { value: "kirsehir", label: "Kırşehir" },
  { value: "kocaeli", label: "Kocaeli" },
  { value: "konya", label: "Konya" },
  { value: "kutahya", label: "Kütahya" },
  { value: "malatya", label: "Malatya" },
  { value: "manisa", label: "Manisa" },
  { value: "kahramanmaras", label: "Kahramanmaraş" },
  { value: "mardin", label: "Mardin" },
  { value: "mugla", label: "Muğla" },
  { value: "mus", label: "Muş" },
  { value: "nevsehir", label: "Nevşehir" },
  { value: "nigde", label: "Niğde" },
  { value: "ordu", label: "Ordu" },
  { value: "rize", label: "Rize" },
  { value: "sakarya", label: "Sakarya" },
  { value: "samsun", label: "Samsun" },
  { value: "siirt", label: "Siirt" },
  { value: "sinop", label: "Sinop" },
  { value: "sivas", label: "Sivas" },
  { value: "tekirdag", label: "Tekirdağ" },
  { value: "tokat", label: "Tokat" },
  { value: "trabzon", label: "Trabzon" },
  { value: "tunceli", label: "Tunceli" },
  { value: "sanliurfa", label: "Şanlıurfa" },
  { value: "usak", label: "Uşak" },
  { value: "van", label: "Van" },
  { value: "yozgat", label: "Yozgat" },
  { value: "zonguldak", label: "Zonguldak" },
  { value: "aksaray", label: "Aksaray" },
  { value: "bayburt", label: "Bayburt" },
  { value: "karaman", label: "Karaman" },
  { value: "kirikkale", label: "Kırıkkale" },
  { value: "batman", label: "Batman" },
  { value: "sirnak", label: "Şırnak" },
  { value: "bartin", label: "Bartın" },
  { value: "ardahan", label: "Ardahan" },
  { value: "igdir", label: "Iğdır" },
  { value: "yalova", label: "Yalova" },
  { value: "karabuk", label: "Karabük" },
  { value: "kilis", label: "Kilis" },
  { value: "osmaniye", label: "Osmaniye" },
  { value: "duzce", label: "Düzce" },
]

export const ilceler = [
  { value: "beyoglu", label: "Beyoğlu" },
  { value: "cubuk", label: "Çubuk" },
  { value: "urla", label: "Urla" },
  { value: "nilufer", label: "Nilüfer" },
  { value: "ceyhan", label: "Ceyhan" },
  { value: "besni", label: "Besni" },
]

export const medeniDurum = [
  { value: "bekar", label: "Bekar" },
  { value: "evli", label: "Evli" },
]

export const yabanciDil = [
  { value: "ingilizce", label: "İngilizce" },
  { value: "almanca", label: "Almanca" },
  { value: "fransizca", label: "Fransızca" },
  { value: "rusca", label: "Rusça" },
  { value: "arapca", label: "Arapça" },
]

export const calismaSekli = [
  { value: "gunduz", label: "Sadece gündüz bakıcılığı" },
  { value: "hsoGunduz", label: "Sadece haftasonu gündüz" },
  { value: "hici", label: "Sadece hafta içi yatılı" },
  { value: "hso", label: "Sadece hafta sonu yatılı" },
  { value: "tum", label: "Pazar dahil tüm günler" },
]

export const deneyim = [
  { value: "deneyim0", label: "0-12 Ay Deneyimli" },
  { value: "deneyim1", label: "1 yıl" },
  { value: "deneyim2", label: "2 yıl" },
  { value: "deneyim3", label: "3 yıl" },
  { value: "deneyim4", label: "4 yıl" },
  { value: "deneyim5", label: "+5 yıl" },
]

export const egitimSev = [
  { value: "doktora", label: "Doktora" },
  { value: "yuksekLi", label: "Yüksek Lisans" },
  { value: "lisans", label: "Lisans" },
  { value: "uni", label: "Universite" },
  { value: "lise", label: "Lise" },
]

export const babySitterInfo = [
  {
    id: 1,
    image: hakkimda_img,
    name: "TUĞBA AKSOY",
    rate: 4.7,
    status: "Güvenilir Bakıcı",
    languge: "İngilizce Konuşabiliyor",
    experience: "2 yıl deneyim",
    info: "İlkyardım Bilgisi",
    workingStatus: "Gündüz Bakıcılığı",
    workingStatus2: "Gece Bakıcılığı",
    price: 1000,
    runtime: "Haftalık",
    workingDays: "(6 gün/24 saat bakım)",
    likes: 7,
  },
  {
    id: 2,
    image: hakkimda_img,
    name: "TUĞBA AKSOY",
    rate: 4.7,
    status: "Güvenilir Bakıcı",
    languge: "İngilizce Konuşabiliyor",
    experience: "2 yıl deneyim",
    info: "İlkyardım Bilgisi",
    workingStatus: "Gündüz Bakıcılığı",
    workingStatus2: "Gece Bakıcılığı",
    price: 1000,
    runtime: "Haftalık",
    workingDays: "(6 gün/24 saat bakım)",
    likes: 7,
  },
  {
    id: 3,
    image: hakkimda_img,
    name: "TUĞBA AKSOY",
    rate: 4.7,
    status: "Güvenilir Bakıcı",
    languge: "İngilizce Konuşabiliyor",
    experience: "2 yıl deneyim",
    info: "İlkyardım Bilgisi",
    workingStatus: "Gündüz Bakıcılığı",
    workingStatus2: "Gece Bakıcılığı",
    price: 1000,
    runtime: "Haftalık",
    workingDays: "(6 gün/24 saat bakım)",
    likes: 7,
  },
]
